INSERT INTO course (
    id,
    title,
    category_id,
    content_id,
    description
) VALUES (
    '4',
    'Finanzas Personales',
    '4',
    '4',
    'Aprenderas estrategias y habitos que mejoraran tu estabilidad financiera. Controlando mejor tus compras, gastos, ahorros e ingresos.'
);

INSERT INTO activity (
    id,
    activity_id,
    content_type,
    title,
    objective,
    metodology,
    resources,
    introduction,
    analisis,
    evaluation,
    example,
    question1,
    question2,
    question3,
    question4,
    question5,
    path,
    course_id
) VALUES (
    10,
    '10',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '4'
);

INSERT INTO activity (
    id,
    activity_id,
    content_type,
    title,
    objective,
    metodology,
    resources,
    introduction,
    analisis,
    evaluation,
    example,
    question1,
    question2,
    question3,
    question4,
    question5,
    path,
    course_id
) VALUES (
    11,
    '11',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '4'
);

INSERT INTO activity (
    id,
    activity_id,
    content_type,
    title,
    objective,
    metodology,
    resources,
    introduction,
    analisis,
    evaluation,
    example,
    question1,
    question2,
    question3,
    question4,
    question5,
    path,
    course_id
) VALUES (
    12,
    '12',
    'comp',
    'Simulador de Finanzas',
    'Desarrollar planes o estrategias para incrementar tus ahorros o encontrar un balance entre ingresos y egresos.',
    '',
    '',
    'Este simulador te permitira tener un vista diferente sobre tus finanzas. ayudandote a ver la importancia de la toma de deciciones sobre las finanzas personales.',
    '',
    'Basado en el equilibrio de ingresos y egresos. Tambien teniendo en cuenta los ahorros o elecciones.',
    '',
    '',
    '',
    '',
    '',
    '',
    '/activity/SimuladorFinanzas',
    '4'
);