INSERT INTO course (
    id,
    title,
    category_id,
    content_id,
    description
) VALUES (
    '3',
    'Organización y Productividad',
    '3',
    '3',
    'Aprenderas tecnicas y estrategias para mejorar tu organización y concentración. Todo para que lo apliques en tus actividades cotidianas.'
);

INSERT INTO activity (
    id,
    activity_id,
    content_type,
    title,
    objective,
    metodology,
    resources,
    introduction,
    analisis,
    evaluation,
    example,
    question1,
    question2,
    question3,
    question4,
    question5,
    path,
    course_id
) VALUES (
    7,
    '7',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '3'
);

INSERT INTO activity (
    id,
    activity_id,
    content_type,
    title,
    objective,
    metodology,
    resources,
    introduction,
    analisis,
    evaluation,
    example,
    question1,
    question2,
    question3,
    question4,
    question5,
    path,
    course_id
) VALUES (
    8,
    '8',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '3'
);

INSERT INTO activity (
    id,
    activity_id,
    content_type,
    title,
    objective,
    metodology,
    resources,
    introduction,
    analisis,
    evaluation,
    example,
    question1,
    question2,
    question3,
    question4,
    question5,
    path,
    course_id
) VALUES (
    9,
    '9',
    'comp',
    'Serpiente Eisenhower',
    'Alcanzar el mayor puntaje posible.',
    'Organizacion y concentración.',
    '',
    'Este juego de la serpiente tienes caracteristicas nuevas, es posible que por su nombre ya tengas una idea de como ganar.',
    '',
    'Segun la cantidad de intentos y tu puntaje, se decidira tu calificación.',
    '',
    '',
    '',
    '',
    '',
    '',
    '/activity/SerpienteEisenhower',
    '3'
);
